name: app
description: It's your data. Take back control.
version: 0.2.2+2
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.3.0
  firebase_dynamic_links: ^2.0.6
  flutter_bloc: ^7.0.1
  flutter_secure_storage: ^4.2.0
  http: ^0.13.3
  package_info: ^2.0.2
  sentry_flutter: ^5.1.0
  shared_preferences: ^2.0.6
  pointycastle: ^3.1.3
  qr_flutter: ^4.0.0
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  android_intent: ^2.0.2
  permission_handler: ^8.1.2
  email_validator: ^2.0.1
  lottie: ^1.1.0
  amplitude_flutter: ^3.2.1
  barcode_scan2: ^4.1.3
  sqflite: ^2.0.0+3
  flutter_markdown: ^0.6.2
  carousel_slider: ^4.0.0
  google_sign_in: ^5.0.4
  googleapis: ^4.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  intl_utils: ^2.3.0
  provider: ^5.0.0
  sizer: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - res/images/
    - res/animation/
    - res/md/
    - res/db/
  fonts:
    - family: TikiIcons
      fonts:
        - asset: res/fonts/tiki_icons.ttf
    - family: Koara
      fonts:
        - asset: res/fonts/Koara-Bold.ttf
          weight: 700
        - asset: res/fonts/Koara-Regular.ttf
        - asset: res/fonts/Koara-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: res/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: res/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: res/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic